### ISSUE TITLE
Andrew's big spec review

### ISSUE THREAD

**Issue by garemoko** [adlnet/xAPI-Spec#798]
This issue lists a number of items to be fixed coming out of a whole spec review. I have pulled some of these out as separate issues as they looked like they could be controversial. I'll do the same for others if they end up being controversial or otherwise requiring discussion. 

I appreciate there's a lot of these, but many of them are very trivial. If we to a point of having few open PRs that coincides with when I have some time. I'll try and tackle a whole bunch of these all at once. 

I'd like to see all of these ticked before we release 1.0.3. 

### Listed for discussion elsewhere
- [ ] The structure of part 3, section 2 seems wrong. The current 2.1 Documents should be later so that the introduction currently in 2.2. introduces section 2 as a whole. Each resource should be brought up to the X.X heading level to avoid imbalance with "2.1 Documents" and having really small headings. See https://github.com/adlnet/xAPI-Spec/issues/799
- [ ] Improvements to introduction as set out in: https://github.com/adlnet/xAPI-Spec/issues/800
- [ ] We already know that Part 1, 5.0 needs work so I skipped over that section. I'll review again when it's done. 
- [ ] https://github.com/adlnet/xAPI-Spec/issues/801
- [ ] In a number of places bulleted lists have inappropriate line spacing between bullets. - Covered in #829

### Global document changes
- [x] Replace "Whilst" with "While" throughout. 

### Not relating to a specific part (or part unknown right now) 
- [x] Requirements for Communities of Practice, currently in part 1 section 7, should be merged into part 2, section 3 (metatda). At the same time, the language should be reviewed in line with existing requirements in part 2, section 3 and the original wording in [4.1.3.2 in the 1.0.3 branch](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#4132-use-in-communities-of-practice). 
- [x] [These metatdata requirements](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#metadata-requirements) have been dropped. presumably the plan was to merge them into part 2, section 3 but this hasn't happened. 
- [x] The section starting "Sections 6 and 7 detail the more technical side of the Experience API" should be re-worded to say "This part details..." and moved to the start of part 3. 
- [x]  "All strings MUST be encoded and interpreted as UTF-8" that is in 1.0.3 is missing in Restructure
- [x] Update link to revision history in Part 3, 3.3 (it's now an appendix)
- [x] Remove "(Came from previous 4.1 Immutability)"
- [x] Add more new lines to [this example](https://github.com/adlnet/xAPI-Spec/blob/1.0.3-Restructure/xAPI.md#example-6)
- [x] Don't use "click here" e.g. "For requirements pertaining to the Timestamp data type, click here."
- [x] The bullet "GET Statements MAY be called using POST and form parameters if necessary as query strings" has a line break before the end of the sentence. 

### Part 1
- [x] Add an explanation of the three parts to part 1, 2.0 How to Use This Document. Also ensure that each part has an introduction that matches this explanation. Strongly consider taking and adapting the text from *5.1 Interoperability Between Components* for this as these two paragraphs essentially describe parts 2 and 3. 
- [x] Split the sentence starting "Whilst these recommendations cannot be MUST requirements" into two sentences. 
- [x] Replace "would have" with "has" in "would have a Base Endpoint of" and possibly elsewhere. 
- [x] "Some communities of practice simply use URL even if they use IRIs, which isn't as technically correct within xAPI." - I'm not sure what this means. I propose deleting it. 
- [x] Add a reference link and fix line formatting on LMS definition. 
- [x] Add section number and full stop to "Implementation details are covered in a later section".
- [x] The heading "Use in Communities of Practice" doesn't make sense under "7.0 Profiles and Communities of Practice. Delete that heading and the Description section immediately below as it just repeats the longer description above. 
- [x] Missing new line at the end of "1.0.2 to 1.0.3 (TBC)" section. 

### Part 2
- [x]  "would not be interoperable with all LRS" should be "LRSs" for the plural. 
- [x] Merge "The LRS MUST reject Statements containing IRL or IRI values without a scheme." into the list of scenarios where the LRS MUST reject above. 
- [x] "Activities referenced by a Statement. " should be "Activity Definitions referenced by a Statement.". This applies in a few other places in that section. 
- [x] "In this scenarios" should be "these"
- [x] Update section number in link "Section 4.1.4.3 When the "Object" is a Statement ". Also update "See StatementRef in 7.3 Statement API)." and "Section 4.3 Voided describes the process". 
- [x] Remove 2.4.3.1 Requirements for Activity Providers as these requirements are covered more generically in 3.2 Hosted Metadata already. Also remove "As with Verbs, it is recommended that Activity Providers look for and use established, widely adopted, Activity types." for the same reason. 
- [x] "Optional in all cases" - delete "in all cases" because it isn't optional in all cases. 
- [x] Delete "Namely, when a conflict with another system occurs, it’s not possible to determine the intentions." because it's unclear.
- [x] Reword "through the use of extensions to an Activity's type and definition"
- [x] "An LRS, upon consuming a valid interactionType, MAY validate the remaining properties as specified in the table below" change to "as specified for Interaction Activities"
- [x] Update "See Section 4.1.2 Actor for details regarding Agents."
- [x] Delete " A common use case for SubStatements would be any experience that would be misleading as its own Statement." as there is more specific detail below and this is too vague to be useful. 
- [x] "A SubStatement MUST NOT contain a SubStatement of their own" - "its own"
- [x] Add a note to "2.4.6.1 Registration Property" to mention that registration is used with the document APIs.
- [x] Replace all instances of "CMI-5" with "cmi5"
- [x] Missing space "The stored property is of type Timestamp.The stored"
- [x] Fix punctuation at end of bullets in 2.4.10 Version client requirements
- [x] Update link "see Section 7.3 "Statement API" for details."

### Part 3
- [x] Add something brief about PUT, POST, GET and DELETE at the start of "1.1 HEAD Request Implementation" to say that these are outlined in relation to the various resources set out in section 2. 
- [x] The requirement "The LRS SHOULD* include a "Last-Modified" header which matches the value of the stored property of the Statement." has been moved to the documents section, but it belongs back in GET Statements because it's about statements. 
- [x]  Update "Section 7.9 Alternate Request Syntax"
- [x] Re-word the first two sentences of Part 3, 2.2 Resources to use the term "resources" instead of "sub-apis". Also update the number to include the about resource. 
- [x] Change "Document APIs" to "Document Resources" to match the new headings. Also applies to "State API", "Activity Profile API" etc. 

__NOTE:__ I didn't test all the links.

**Comment by garemoko** [comment]
I'm unable to find a reference for the LMS definition - I'm hitting citogenesis. I'm just going to fix the formatting issue and leave it without a link.

**Comment by garemoko** [comment]
Closing this as everything is either done, has an active PR or is Listed for discussion elsewhere.
